version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: lanchonete_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lanchonete_db
      POSTGRES_USER: lanchonete_user
      POSTGRES_PASSWORD: lanchonete_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "log_statement=all"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-controle-pedidos-lanchonete-app
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
