spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lanchonete_db
    username: lanchonete_user
    password: lanchonete_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
